[versions]
agp = "8.7.1"
material = "1.12.0"
gson = "2.11.0"

[libraries]
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

